[theme]
primaryColor="#000000"
backgroundColor="#f9f9f9"
secondaryBackgroundColor="#ededed"
textColor="#000000"
font="sans serif"

[global]

[client]
showSidebarNavigation = true

[server]
runOnSave = true