[theme]
primaryColor="#000000"
backgroundColor="#f2f2f2"
secondaryBackgroundColor="#ededed"
textColor="#000000"
font="sans serif"

[global]

[client]
showSidebarNavigation = true

[server]
runOnSave = true